# Generated by Django 3.1 on 2022-09-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='body',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
